CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku VARCHAR(40) NOT NULL UNIQUE,
    name VARCHAR(160) NOT NULL,
    description VARCHAR(500) NOT NULL,
    unit_price DECIMAL(19, 4) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS suppliers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(40) NOT NULL UNIQUE,
    name VARCHAR(160) NOT NULL,
    contact_name VARCHAR(160) NOT NULL,
    email VARCHAR(200) NOT NULL,
    phone VARCHAR(60) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS product_suppliers (
    product_id BIGINT NOT NULL,
    supplier_id BIGINT NOT NULL,
    PRIMARY KEY (product_id, supplier_id),
    CONSTRAINT fk_product_suppliers_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fk_product_suppliers_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(id)
);

CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR(160) NOT NULL,
    description VARCHAR(500) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    product_id BIGINT,
    product_name VARCHAR(160) NOT NULL,
    quantity INTEGER NOT NULL,
    unit_price DECIMAL(19, 4) NOT NULL,
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
);

INSERT INTO products (sku, name, description, unit_price, active)
SELECT 'PAP-001', 'Studio notebook', 'Recycled paper, 160 pages', 12.50, TRUE
WHERE NOT EXISTS (SELECT 1 FROM products WHERE sku = 'PAP-001');

INSERT INTO products (sku, name, description, unit_price, active)
SELECT 'DES-014', 'Desk lamp', 'Warm dimmable light, matte green', 48.00, TRUE
WHERE NOT EXISTS (SELECT 1 FROM products WHERE sku = 'DES-014');

INSERT INTO products (sku, name, description, unit_price, active)
SELECT 'KIT-220', 'Ceramic mug set', 'Set of two hand-glazed mugs', 26.75, TRUE
WHERE NOT EXISTS (SELECT 1 FROM products WHERE sku = 'KIT-220');

INSERT INTO products (sku, name, description, unit_price, active)
SELECT 'ACC-032', 'Canvas tote', 'Heavyweight cotton, natural finish', 18.00, TRUE
WHERE NOT EXISTS (SELECT 1 FROM products WHERE sku = 'ACC-032');

INSERT INTO suppliers (code, name, contact_name, email, phone, active)
SELECT 'SUP-001', 'Northstar Paper Co.', 'Maya Chen', 'orders@northstarpaper.example', '+1 555 0140', TRUE
WHERE NOT EXISTS (SELECT 1 FROM suppliers WHERE code = 'SUP-001');

INSERT INTO suppliers (code, name, contact_name, email, phone, active)
SELECT 'SUP-002', 'Greenline Homeware', 'Luca Ferri', 'sales@greenline.example', '+39 02 555 0198', TRUE
WHERE NOT EXISTS (SELECT 1 FROM suppliers WHERE code = 'SUP-002');

INSERT INTO product_suppliers (product_id, supplier_id)
SELECT p.id, s.id FROM products p, suppliers s
WHERE p.sku IN ('PAP-001', 'ACC-032') AND s.code = 'SUP-001'
    AND NOT EXISTS (SELECT 1 FROM product_suppliers ps WHERE ps.product_id = p.id AND ps.supplier_id = s.id);

INSERT INTO product_suppliers (product_id, supplier_id)
SELECT p.id, s.id FROM products p, suppliers s
WHERE p.sku IN ('DES-014', 'KIT-220') AND s.code = 'SUP-002'
    AND NOT EXISTS (SELECT 1 FROM product_suppliers ps WHERE ps.product_id = p.id AND ps.supplier_id = s.id);